name: Mirror docker images on Zenodo

on:
  repository_dispatch:
    types:
      - 'mirror-zenodo/*-*-*'
      - 'mirrors/*-*-*'
  push:
    tags:
      - '*-*-*'
    branches:
      - zenodo-mirror


jobs:
  mirror-zenodo:
    name: Release on Zenodo
    runs-on: ubuntu-latest
    steps:
      - run:
          echo ZENODO_TOKEN=${{secrets.ZENODO_TOKEN}} >> $GITHUB_ENV
        if: ! contains('--sandbox', '${{vars.DONODO_FLAGS}}')
      - run:
          echo ZENODO_TOKEN=${{secrets.ZENODO_SANDBOX_TOKEN}} >> $GITHUB_ENV
        if: contains('--sandbox', '${{vars.DONODO_FLAGS}}')
      - run:
          echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
        if: github.event_name == 'push'
      - run:
          echo TAG=${REF##*/} >> $GITHUB_ENV
        if: github.event_name == 'repository_dispatch'
        env:
            REF: ${{ github.event.action }}
      - run:
          echo IMAGE=${{vars.COLOMOTO_DOCKER_IMAGE}}:${TAG} >> $GITHUB_ENV
      - name: Setup Donodo
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - run: pip install donodo
      - run: docker pull ${IMAGE}
      - run: donodo ${{vars.DONODO_FLAGS}} push $IMAGE
